### ISSUE TITLE
How to get cpu and ram utilisation without workers

### ISSUE THREAD

**Issue by Debaghya** [vokash3/LocustExporter#1]
Need source code and corresponding json file where there are no workers but still want to display cpu and ram utilisation

**Comment by Debaghya** [comment]
Any help would be appreciated

**Comment by vokash3** [comment]
Hello! Unfortunately, Locust doesn't collect any utilization from master or when working without workers. If you wanna get this information any way you can monitor your main machine separately, for example, using telegraf, influxdb and grafana (just one of some possible ways) or node exporter + prometheus + grafana (one more variant).
